class DQIXConstants:
    # Commonly used data and their sizes
    ITEM_TYPE_SIZE = 2
    ITEM_AMOUNT_SIZE = 1
    GOLD_VALUE_SIZE = 4

    ITEM_DATA_NO_ITEM = 65535

    GOLD_IN_BANK = 0x0F6D44
    GOLD_AT_HAND = 0x0F6D48

    # Common Items (Bag)
    COMMON_ITEMS_TYPE_OFFSET = 0x0F5DE8
    COMMON_ITEMS_COUNTS_OFFSET = 0x0F5F18
    COMMON_ITEMS_SEGMENTS = 152

    # Weapons (Bag)
    WEAPONS_TYPE_OFFSET = 0x0F5FB0
    WEAPONS_COUNTS_OFFSET = 0x0F61D0
    WEAPONS_SEGMENTS = 272

    # Shields (Bag)
    SHIELDS_TYPE_OFFSET = 0x0F62E0
    SHIELDS_COUNTS_OFFSET = 0x0F6340
    SHIELDS_SEGMENTS = 48

    # Torso (Bag)
    TORSO_TYPE_OFFSET = 0x0F6370
    TORSO_COUNTS_OFFSET = 0x0F64F0
    TORSO_SEGMENTS = 192

    # Legs (Bag)
    LEGS_TYPE_OFFSET = 0x0F65B0
    LEGS_COUNTS_OFFSET = 0x0F6670
    LEGS_SEGMENTS = 96

    # Headwear (Bag)
    HEADWEAR_TYPE_OFFSET = 0x0F66D0
    HEADWEAR_COUNTS_OFFSET = 0x0F67F0
    HEADWEAR_SEGMENTS = 144

    # Arms (Bag)
    ARMS_TYPE_OFFSET = 0x0F6880
    ARMS_COUNTS_OFFSET = 0x0F6920
    ARMS_SEGMENTS = 80

    # Footwear (Bag)
    FOOTWEAR_TYPE_OFFSET = 0x0F6970
    FOOTWEAR_COUNTS_OFFSET = 0x0F6A50
    FOOTWEAR_SEGMENTS = 112

    # Accessories (Bag)
    ACCESSORIES_TYPE_OFFSET = 0x0F6AC0
    ACCESSORIES_COUNTS_OFFSET = 0x0F6B40
    ACCESSORIES_SEGMENTS = 64

    # Important Items (Bag)
    IMPORTANT_ITEMS_TYPE_OFFSET = 0x0F6BEC
    IMPORTANT_ITEMS_COUNTS_OFFSET = 0x0F6CA8
    IMPORTANT_ITEMS_SEGMENTS = 94

    # ----- Not yet used -----

    DQVC_MESSAGE_OFFSET = 0x0F9358
    DQVC_MESSAGE_LENGTH = 510

    VISITED_LOCATIONS_OFFSET = 0x108910
    VISITED_LOCATIONS_SIZE = 3

    LEARNED_PARTY_TRICKS_OFFSET = 0x108A50
    LEARNED_PARTY_TRICKS_SIZE = 4

    UNLOCKABLE_VOCATIONS_OFFSET = 0x108AF8
    UNLOCKABLE_VOCATIONS_SIZE = 2

    SPENT_MINIMEDALS_OFFSET = 0x0F5F7C
    SPENT_MINIMEDALS_SIZE = 4
